#!/bin/bash
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
install lazygit -D -t ~/bin/
rm lazygit.tar.gz lazygit
chmod a+x ./clone-repo.sh
echo 'git config --global user.name "Bikash"' >> ~/.bashrc
echo 'git config --global user.email "bikashprakashdash@gmail.com"' >> ~/.bashrc
